---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-external-creds
  namespace: ck-prod
type: Opaque
stringData:
  username: postgres
  password: "__{{database.postgres.ck-prod.accounts:f:postgres}}__"
