---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ariang
  namespace: default
  labels:
    app.kubernetes.io/name: ariang
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ariang
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ariang
    spec:
      containers:
        - name: app
          image: cloudpublic/default/ariang:latest
          imagePullPolicy: Always
          ports:
            - name: default
              containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ariang
  namespace: default
  labels:
    app.kubernetes.io/name: ariang
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: default
  selector:
    app.kubernetes.io/name: ariang

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ariang
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: middleware-playonjan@kubernetescrd,middleware-antimitm@kubernetescrd,sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/name: Ariang
    gethomepage.dev/icon: https://ariang.__{{infra.domains:f:x}}__/favicon.png
    gethomepage.dev/href: https://ariang.__{{infra.domains:f:x}}__
    gethomepage.dev/siteMonitor: https://ariang.__{{infra.domains:f:x}}__
    gethomepage.dev/weight: "40"
spec:
  ingressClassName: traefik
  rules:
    - host: ariang.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ariang
                port:
                  name: default
  tls:
    - hosts:
        - ariang.__{{infra.domains:f:x}}__
      secretName: ariang-domainx
