---
apiVersion: v1
kind: Secret
metadata:
  name: __((name))__-box-password
  namespace: default
type: Opaque
data:
  password: __{{koishi.machine.devbox-nur:_:b64}}__

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __((name))__
  namespace: default
  labels:
    app: __((name))__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __((name))__
  template:
    metadata:
      labels:
        app: __((name))__
    spec:
      nodeSelector:
        kubernetes.io/hostname: __((run-on-host))__
      hostname: devbox-__((run-on-host))__
      securityContext:
        supplementalGroups:
          - 988
      volumes:
        - name: coder-workspaces
          persistentVolumeClaim:
            claimName: nfs-disk-coder-workspaces
        - name: coder-workspaces-local
          hostPath:
            path: /mnt/coder-workspaces
            type: DirectoryOrCreate

        - name: coder-sharepoint
          persistentVolumeClaim:
            claimName: nfs-disk-coder-sharepoint
        - name: coder-sharepoint-local
          hostPath:
            path: /mnt/coder-sharepoint
            type: DirectoryOrCreate

        - name: user-data-slight
          persistentVolumeClaim:
            claimName: nfs-disk-user-data-slight

        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

      containers:
        - name: app
          image: cloudpublic/default/devbox:latest
          imagePullPolicy: Always
          command: ["bash", "/home/box/entrypoint.root.sh"]
          env:
            - name: BOX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: __((name))__-box-password
                  key: password
          volumeMounts:
            - name: coder-workspaces
              mountPath: /mnt/coder-workspaces

            - name: user-data-slight
              mountPath: /mnt/user-data-slight

            - name: coder-sharepoint
              mountPath: /mnt/coder-sharepoint
            - name: coder-sharepoint-local
              mountPath: /mnt/coder-sharepoint-local

            - name: docker-sock
              mountPath: /var/run/docker.sock

            - name: coder-workspaces
              subPath: private-workspace/repos/local/polyphony/koishi/devbox/default.nix
              mountPath: /home/box/default.nix
            - name: coder-workspaces
              subPath: private-workspace/repos/local/polyphony/koishi/devbox/default.editor.nix
              mountPath: /home/box/default.editor.nix
            - name: coder-workspaces
              subPath: private-workspace/repos/local/polyphony/koishi/devbox/entrypoint.root.sh
              mountPath: /home/box/entrypoint.root.sh
            - name: coder-workspaces
              subPath: private-workspace/repos/local/polyphony/koishi/devbox/entrypoint.box.sh
              mountPath: /home/box/entrypoint.box.sh

            - name: coder-workspaces
              mountPath: /home/box/.doom.d
              subPath: private-workspace/repos/local/doom.d
            - name: coder-workspaces
              mountPath: /home/box/.zsh
              subPath: public-workspace/system/zsh # .zhistory is not suitable for symbolic link
            - name: coder-workspaces
              mountPath: /home/box/.ssh
              subPath: private-workspace/workspace/encrypted-configs/.ssh # for something unknown reason, .ssh/authroized_keys is not working if symbol link

            - name: coder-workspaces-local
              mountPath: /home/box/.cache/huggingface
              subPath: public-workspace/cache-global/huggingface
            - name: coder-workspaces-local
              mountPath: /home/box/.config/emacs
              subPath: public-workspace/editor/emacs.d
          ports:
            - containerPort: 22
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 120
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: __((name))__
  namespace: default
  labels:
    app: __((name))__
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  selector:
    app: __((name))__
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ssh
      port: __((tcp-port))__
      protocol: TCP
      targetPort: 22
