---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: chameleon
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
