import { NextRequest, NextResponse } from "next/server";
import { getSession, addMessage } from "@/lib/store";
import { eventBus } from "@/lib/event-bus";
import { controllerManager } from "@/lib/controller-manager";

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getSession(id);

  if (!session) {
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }

  try {
    const prTitle = `Itero: ${session.prompt.slice(0, 50)}`;
    const prBody = `Automated PR generated by Itero AI agent.\n\n**Session prompt:**\n${session.prompt}`;

    const controllerId = controllerManager.resolveControllerId(session.controllerId);
    if (!controllerId) {
      return NextResponse.json({ error: "No connected controller available" }, { status: 503 });
    }

    const result = await controllerManager.sendRequest(
      controllerId,
      "git.pr.create",
      { workDir: session.repoPath, title: prTitle, body: prBody },
      60_000
    );

    const prUrl = result.prUrl;

    const msg = await addMessage({
      sessionId: id,
      role: "system",
      content: `🎉 Pull Request created successfully!\nURL: ${prUrl}`,
      type: "system-info",
    });
    eventBus.publish({ type: "message_added", payload: msg });

    return NextResponse.json({ success: true, prUrl });
  } catch (error: any) {
    console.error("PR Creation error for session:", error);
    const errorMessage = error.message || String(error);

    const msg = await addMessage({
      sessionId: id,
      role: "system",
      content: `❌ Failed to create Pull Request: ${errorMessage}`,
      type: "system-error",
    });
    eventBus.publish({ type: "message_added", payload: msg });

    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
