import { NextRequest, NextResponse } from "next/server";
import { getSession, updateSession, addMessage } from "@/lib/store";
import { exec } from "child_process";
import { promisify } from "util";
import { eventBus } from "@/lib/event-bus";

const execAsync = promisify(exec);

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getSession(id);

  if (!session) {
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }

  const hasToken = !!(process.env.GITHUB_TOKEN || process.env.GH_TOKEN);
  if (!hasToken) {
    return NextResponse.json({ error: "GitHub configuration missing (GITHUB_TOKEN)" }, { status: 400 });
  }

  try {
    const cwd = session.repoPath;
    
    // 1. Get current branch name
    const { stdout: branchStdout } = await execAsync("git branch --show-current", { cwd });
    const branchName = branchStdout.trim();
    if (!branchName) {
      throw new Error("Could not detect current git branch name from the repository");
    }

    // 2. Prepare environment variables
    const env = {
      ...process.env,
      GITHUB_TOKEN: process.env.GITHUB_TOKEN || process.env.GH_TOKEN,
      GH_TOKEN: process.env.GITHUB_TOKEN || process.env.GH_TOKEN,
    };
    
    // 3. Push current branch to remote origin
    await execAsync(`git push -u origin ${branchName}`, { cwd, env });

    // 4. Create Pull Request using GitHub CLI (gh)
    const prTitle = `Itero: ${session.prompt.slice(0, 50)}`;
    const prBody = `Automated PR generated by Itero AI agent.\n\n**Session prompt:**\n${session.prompt}`;
    
    const { stdout: prStdout } = await execAsync(
      `gh pr create --title "${prTitle.replace(/"/g, '\\"')}" --body "${prBody.replace(/"/g, '\\"')}" --head ${branchName}`,
      { cwd, env }
    );

    // Extract PR URL from output
    const match = prStdout.match(/https:\/\/github\.com\/[^\s/]+\/[^\s/]+\/pull\/\d+/);
    const prUrl = match?.[0] || prStdout.trim();

    if (!prUrl.startsWith("https://")) {
      throw new Error(`Failed to create PR. Command output was: ${prStdout}`);
    }

    // Add system notification message
    const msg = await addMessage({
      sessionId: id,
      role: "system",
      content: `🎉 Pull Request created successfully!\nURL: ${prUrl}`,
    });
    
    eventBus.publish({ type: "message_added", payload: msg });

    return NextResponse.json({ success: true, prUrl });
  } catch (error: any) {
    console.error("PR Creation error for session:", error);
    const errorMessage = error.message || String(error);
    
    const msg = await addMessage({
      sessionId: id,
      role: "system",
      content: `❌ Failed to create Pull Request: ${errorMessage}`,
    });
    eventBus.publish({ type: "message_added", payload: msg });
    
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
