---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: default
  labels:
    app.kubernetes.io/name: n8n
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  template:
    metadata:
      labels:
        app.kubernetes.io/name: n8n
    spec:
      volumes:
        - name: default-common
          persistentVolumeClaim:
            claimName: default-common-encrypted
      containers:
        - name: app
          image: docker.n8n.io/n8nio/n8n
          env:
            - name: WEBHOOK_URL
              value: "https://n8n.__{{infra.domains:f:x}}__"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.__{{infra.domains:f:x}}__"
          volumeMounts:
            - name: default-common
              subPath: n8n/data
              mountPath: /home/node/.n8n
          ports:
            - name: default
              protocol: TCP
              containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - name: default
      port: 80
      targetPort: default
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: middleware-playonjan@kubernetescrd,middleware-antimitm@kubernetescrd,sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: AI
    gethomepage.dev/name: n8n
    gethomepage.dev/icon: https://n8n.io/favicon.ico
    gethomepage.dev/href: https://n8n.__{{infra.domains:f:x}}__
    gethomepage.dev/siteMonitor: https://n8n.__{{infra.domains:f:x}}__
    gethomepage.dev/weight: "5"
spec:
  ingressClassName: traefik
  rules:
    - host: n8n.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  name: default
  tls:
    - hosts:
        - n8n.__{{infra.domains:f:x}}__
      secretName: n8n

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-oauth-callback
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
spec:
  ingressClassName: traefik
  rules:
    - host: n8n.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /rest/oauth2-credential/callback
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  name: default
  tls:
    - hosts:
        - n8n.__{{infra.domains:f:x}}__
      secretName: n8n
