---
apiVersion: v1
kind: Namespace
metadata:
  name: sablier

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sablier
  namespace: sablier

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sablier
rules:
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments
      - statefulsets
    verbs:
      - get # Retrieve info about specific dep
      - list # Events
      - watch # Events
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - patch # Scale up and down
      - update # Scale up and down
      - get # Retrieve info about specific dep
      - list # Events
      - watch # Events

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sablier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sablier
subjects:
  - kind: ServiceAccount
    name: sablier
    namespace: sablier

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sablier
  namespace: sablier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sablier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sablier
    spec:
      serviceAccountName: sablier
      containers:
        - name: sablier
          image: sablierapp/sablier:1.11.1
          args:
            - "start"
            - "--provider.name=kubernetes"
          ports:
            - name: http
              containerPort: 10000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: sablier
  namespace: sablier
spec:
  selector:
    app.kubernetes.io/name: sablier
  ports:
    - name: http
      port: 80
      targetPort: 10000
