---
apiVersion: v1
kind: Service
metadata:
  name: devbox-nur-arondo-dev
  namespace: default
  labels:
    app: devbox-nur-arondo-dev
spec:
  type: ClusterIP
  selector:
    app: devbox-nur
  ports:
    - name: default
      port: 3251
      protocol: TCP
      targetPort: 3251

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arondo-dev
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: middleware-playonjan@kubernetescrd,middleware-antimitm@kubernetescrd,sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: AI
    gethomepage.dev/name: Arondo Dev
    gethomepage.dev/href: https://arondo-dev.__{{infra.domains:f:x}}__/
    gethomepage.dev/weight: "80"
spec:
  ingressClassName: traefik
  rules:
    - host: arondo-dev.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devbox-nur-arondo-dev
                port:
                  name: default
  tls:
    - hosts:
        - arondo-dev.__{{infra.domains:f:x}}__
      secretName: arondo-dev-domainx
