---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
    resourceNames: ["rclone"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-role-binding
subjects:
  - kind: ServiceAccount
    name: backup-sa
roleRef:
  kind: Role
  name: backup-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-prepare
  namespace: default
  labels:
    app: backup-prepare
spec:
  schedule: "0 18 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: backup-prepare
        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/hostname: nur
          volumes:
            - name: backup-scripts
              hostPath:
                path: /mnt/coder-workspaces/private-workspace/repos/local/polyphony/koishi/media/backup/scripts
                type: Directory
            - name: backup-cache
              emptyDir:
                sizeLimit: 30Gi

            - name: backup-source-plex
              hostPath:
                path: /mnt/runtime-data-app/plex/database/Library/Application Support/Plex Media Server
                type: Directory
            - name: backup-source-coder
              hostPath:
                path: /mnt/coder-workspaces
                type: Directory

            - name: ebackup-upload
              hostPath:
                path: /mnt/user-data-others/ebackup/upload
                type: Directory

          containers:
            - name: app
              image: cloudpublic/default/backup:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - |
                  python3 -u /backup-scripts/backup.py
              env:
                - name: POSTGRES_HOST
                  value: db-postgres-prod.my-database
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_USER
                  value: postgres
                - name: POSTGRES_PASSWORD
                  value: "__{{database.postgres.accounts:f:postgres}}__"
              volumeMounts:
                - name: backup-scripts
                  mountPath: /backup-scripts
                  readOnly: true

                - name: backup-cache
                  mountPath: /mnt/backup-cache

                - name: backup-source-plex
                  mountPath: /mnt/backup-source/plex
                  readOnly: true
                - name: backup-source-coder
                  mountPath: /mnt/backup-source/coder-workspaces
                  readOnly: true

                - name: ebackup-upload
                  mountPath: /mnt/user-data-others/ebackup/upload
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-upload
  namespace: default
  labels:
    app: backup-upload
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: backup-upload
        spec:
          restartPolicy: Never
          serviceAccountName: backup-sa
          containers:
            - name: app
              image: bitnami/kubectl:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - |
                  kubectl exec deploy/rclone -- sh -c "python3 -u /backup-scripts/rclone.py backup-latest --offset-days 7"
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
