---
apiVersion: v1
kind: Namespace
metadata:
  name: ck-fountain-prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: ck-fountain-prod
  labels:
    app.kubernetes.io/name: scanner
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scanner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scanner
    spec:
      containers:
        - name: app
          image: cloudpublic/ck/fountain/scanner:latest
          imagePullPolicy: Always
          ports:
            - name: default
              containerPort: 80
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: ck-fountain-prod
  labels:
    app.kubernetes.io/name: scanner
  annotations:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scanner
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: default

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scanner
  namespace: ck-fountain-prod
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Fountain
    gethomepage.dev/href: https://fountain.__{{infra.domains:f:c}}__/scanner
    gethomepage.dev/siteMonitor: https://fountain.__{{infra.domains:f:c}}__/scanner
    gethomepage.dev/weight: "10"
spec:
  ingressClassName: traefik
  rules:
    - host: fountain.__{{infra.domains:f:c}}__
      http:
        paths:
          - path: /scanner
            pathType: Prefix
            backend:
              service:
                name: scanner
                port:
                  name: default
  tls:
    - hosts:
        - fountain.__{{infra.domains:f:c}}__
      secretName: ck-fountain-prod-scanner
