---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  namespace: chameleon
data:
  squid.conf: |
    # Squid proxy configuration for domain-based filtering
    # Port configuration
    http_port 3128

    # DNS configuration
    dns_nameservers 8.8.8.8 8.8.4.4

    # Access control lists (ACLs)
    acl localnet src 10.0.0.0/8     # RFC1918 possible internal network
    acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
    acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
    acl localnet src fc00::/7        # RFC 4193 local private network range
    acl localnet src fe80::/10       # RFC 4291 link-local (directly plugged) machines

    # Safe ports
    acl SSL_ports port 443
    acl Safe_ports port 80          # http
    acl Safe_ports port 21          # ftp
    acl Safe_ports port 443         # https
    acl Safe_ports port 70          # gopher
    acl Safe_ports port 210         # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280         # http-mgmt
    acl Safe_ports port 488         # gss-http
    acl Safe_ports port 591         # filemaker
    acl Safe_ports port 777         # multiling http

    acl CONNECT method CONNECT

    # Domain whitelist - only allow these domains
    acl allowed_domains dstdomain "/etc/squid/allowed_domains.txt"

    # Default deny all, then allow specific domains
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localhost manager
    http_access deny manager
    http_access allow localnet allowed_domains
    http_access allow localhost allowed_domains
    http_access deny all

    # Logging
    access_log /var/log/squid/access.log squid
    cache_log /var/log/squid/cache.log

    # Cache configuration - minimal caching for better domain control
    cache_mem 64 MB
    maximum_object_size_in_memory 512 KB
    maximum_object_size 4 MB
    cache_dir null /tmp

    # Don't cache anything to ensure fresh domain checks
    cache deny all

    # Forwarded headers
    forwarded_for on
    via on

    # Error pages - disable HTML error pages for simple HTTP status codes
    deny_info TCP_RESET all

    # Refresh patterns
    refresh_pattern ^ftp:           1440    20%     10080
    refresh_pattern ^gopher:        1440    0%      1440
    refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
    refresh_pattern .               0       20%     4320

    # Shutdown lifetime
    shutdown_lifetime 3 seconds

  allowed_domains.txt: |
    .google.com
    .googleapis.com
    .github.com
    .githubusercontent.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: chameleon
  labels:
    app.kubernetes.io/name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: squid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: squid-config
          configMap:
            name: squid-config
      containers:
        - name: app
          image: ubuntu/squid:latest
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 3128
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: squid-config
              mountPath: /etc/squid/allowed_domains.txt
              subPath: allowed_domains.txt
          livenessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: chameleon
  labels:
    app.kubernetes.io/name: squid
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: squid
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
      protocol: TCP
