---
apiVersion: v1
kind: Secret
metadata:
  name: gphotosync-sshkeys-system
  namespace: default
type: Opaque
data:
  ssh_host_ecdsa_key: __{{gphotosync.sshkeys.system.files:a:ssh_host_ecdsa_key:a:b64}}__
  ssh_host_ecdsa_key.pub: __{{gphotosync.sshkeys.system.files:a:ssh_host_ecdsa_key.pub:a:b64}}__
  ssh_host_ed25519_key: __{{gphotosync.sshkeys.system.files:a:ssh_host_ed25519_key:a:b64}}__
  ssh_host_ed25519_key.pub: __{{gphotosync.sshkeys.system.files:a:ssh_host_ed25519_key.pub:a:b64}}__
  ssh_host_rsa_key: __{{gphotosync.sshkeys.system.files:a:ssh_host_rsa_key:a:b64}}__
  ssh_host_rsa_key.pub: __{{gphotosync.sshkeys.system.files:a:ssh_host_rsa_key.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: gphotosync-sshkeys-user-hh
  namespace: default
type: Opaque
data:
  authorized_keys: __{{gphotosync.sshkeys.hh.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{gphotosync.sshkeys.hh.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{gphotosync.sshkeys.hh.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: gphotosync-sshkeys-user-cc
  namespace: default
type: Opaque
data:
  authorized_keys: __{{gphotosync.sshkeys.cc.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{gphotosync.sshkeys.cc.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{gphotosync.sshkeys.cc.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: gphotosync-sshkeys-user-001
  namespace: default
type: Opaque
data:
  authorized_keys: __{{gphotosync.sshkeys.001.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{gphotosync.sshkeys.001.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{gphotosync.sshkeys.001.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gphotosync
  namespace: default
  labels:
    app: gphotosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gphotosync
  template:
    metadata:
      labels:
        app: gphotosync
    spec:
      nodeSelector:
        kubernetes.io/hostname: nur
      volumes:
        - name: data
          hostPath:
            path: /mnt/user-data-slight/private-data/gphotosync
            type: Directory
        - name: gphotosync-sshkeys-user-hh
          secret:
            secretName: gphotosync-sshkeys-user-hh
            defaultMode: 0600
        - name: gphotosync-sshkeys-user-cc
          secret:
            secretName: gphotosync-sshkeys-user-cc
            defaultMode: 0600
        - name: gphotosync-sshkeys-user-001
          secret:
            secretName: gphotosync-sshkeys-user-001
            defaultMode: 0600
        - name: gphotosync-sshkeys-system
          secret:
            secretName: gphotosync-sshkeys-system
            defaultMode: 0600
      containers:
        - name: app
          image: cloudpublic/default/gphotosync:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /mnt/user-data-slight/gphotosync
            - name: gphotosync-sshkeys-user-hh
              mountPath: /tmp/gphotosync-sshkeys-user-hh
            - name: gphotosync-sshkeys-user-cc
              mountPath: /tmp/gphotosync-sshkeys-user-cc
            - name: gphotosync-sshkeys-user-001
              mountPath: /tmp/gphotosync-sshkeys-user-001
            - name: gphotosync-sshkeys-system
              mountPath: /tmp/gphotosync-sshkeys-system
          ports:
            - containerPort: 22
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
# kubecutl expose deployment gphotosync --port 3739 --target-port 22 --name gphotosync --type=LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: gphotosync
  namespace: default
  labels:
    app: gphotosync
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 37000
      protocol: TCP
      targetPort: 22
  selector:
    app: gphotosync
