---
apiVersion: v1
kind: Namespace
metadata:
  name: external-cockpit

---
apiVersion: v1
kind: Service
metadata:
  name: cockpit
  namespace: external-cockpit
spec:
  ports:
    - name: default
      port: 80

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: cockpit
  namespace: external-cockpit
  labels:
    kubernetes.io/service-name: cockpit
addressType: IPv4
ports:
  - name: default
    port: 9090
    protocol: TCP
endpoints:
  - addresses:
      - "__{{infra.machine.nur:f:ip}}__"
    conditions:
      ready: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cockpit
  namespace: external-cockpit
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: System
    gethomepage.dev/name: cockpit
    gethomepage.dev/icon: cockpit
    gethomepage.dev/href: https://cockpit-nur.__{{infra.domains:f:x}}__/
    gethomepage.dev/siteMonitor: https://cockpit-nur.__{{infra.domains:f:x}}__/
    gethomepage.dev/weight: "0"
spec:
  ingressClassName: traefik
  rules:
    - host: cockpit-nur.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cockpit
                port:
                  name: default
  tls:
    - hosts:
        - cockpit-nur.__{{infra.domains:f:x}}__
      secretName: cockpit-nur-domainx
