---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web-automated
  namespace: default
  labels:
    app.kubernetes.io/name: calibre-web-automated
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre-web-automated
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre-web-automated
    spec:
      terminationGracePeriodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: nur
      volumes:
        - name: config
          hostPath:
            path: /mnt/runtime-data-app/calibre-web-automated
            type: DirectoryOrCreate
        - name: calibre-library
          hostPath:
            path: /mnt/user-data-others/data/Book/calibre
            type: DirectoryOrCreate
        - name: cwa-book-ingest
          hostPath:
            path: /mnt/user-data-others/data/Book/cwa-book-ingest
            type: DirectoryOrCreate
      containers:
        - name: app
          image: crocodilestick/calibre-web-automated:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: calibre-library
              mountPath: /calibre-library
            - name: cwa-book-ingest
              mountPath: /cwa-book-ingest
          ports:
            - name: default
              containerPort: 8083
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web-automated
  namespace: default
  labels:
    app.kubernetes.io/name: calibre-web-automated
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calibre-web-automated
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: default

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web-automated
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: middleware-playonjan@kubernetescrd,middleware-antimitm@kubernetescrd,sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/name: calibre-web
    gethomepage.dev/icon: calibre-web
    gethomepage.dev/href: https://calibre.__{{infra.domains:f:x}}__
    gethomepage.dev/siteMonitor: https://calibre.__{{infra.domains:f:x}}__
    gethomepage.dev/weight: "5"
spec:
  ingressClassName: traefik
  rules:
    - host: calibre.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web-automated
                port:
                  name: default
  tls:
    - hosts:
        - calibre.__{{infra.domains:f:x}}__
      secretName: calibre-domainx
