---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablierdownload
  namespace: default
spec:
  plugin:
    sablier:
      sablierUrl: "http://sablier.sablier"
      group: "download"
      sessionDuration: "1h"
      dynamic:
        theme: "ghost"
        showDetails: true
