---
apiVersion: v1
kind: Secret
metadata:
  name: foldersync-sshkeys-system
  namespace: default
type: Opaque
data:
  ssh_host_ecdsa_key: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_ecdsa_key:a:b64}}__
  ssh_host_ecdsa_key.pub: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_ecdsa_key.pub:a:b64}}__
  ssh_host_ed25519_key: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_ed25519_key:a:b64}}__
  ssh_host_ed25519_key.pub: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_ed25519_key.pub:a:b64}}__
  ssh_host_rsa_key: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_rsa_key:a:b64}}__
  ssh_host_rsa_key.pub: __{{koishi.foldersync.sshkeys.system.files:a:ssh_host_rsa_key.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: foldersync-sshkeys-user-hh
  namespace: default
type: Opaque
data:
  authorized_keys: __{{koishi.foldersync.sshkeys.hh.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{koishi.foldersync.sshkeys.hh.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{koishi.foldersync.sshkeys.hh.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: foldersync-sshkeys-user-cc
  namespace: default
type: Opaque
data:
  authorized_keys: __{{koishi.foldersync.sshkeys.cc.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{koishi.foldersync.sshkeys.cc.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{koishi.foldersync.sshkeys.cc.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: v1
kind: Secret
metadata:
  name: foldersync-sshkeys-user-001
  namespace: default
type: Opaque
data:
  authorized_keys: __{{koishi.foldersync.sshkeys.001.files:a:id_rsa.pub:a:b64}}__
  id_rsa: __{{koishi.foldersync.sshkeys.001.files:a:id_rsa:a:b64}}__
  id_rsa.pub: __{{koishi.foldersync.sshkeys.001.files:a:id_rsa.pub:a:b64}}__

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldersync
  namespace: default
  labels:
    app: foldersync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foldersync
  template:
    metadata:
      labels:
        app: foldersync
    spec:
      nodeSelector:
        kubernetes.io/hostname: nur
      volumes:
        - name: foldersync-sshkeys-user-hh
          secret:
            secretName: foldersync-sshkeys-user-hh
            defaultMode: 0600
        - name: foldersync-sshkeys-user-cc
          secret:
            secretName: foldersync-sshkeys-user-cc
            defaultMode: 0600
        - name: foldersync-sshkeys-user-001
          secret:
            secretName: foldersync-sshkeys-user-001
            defaultMode: 0600
        - name: foldersync-sshkeys-system
          secret:
            secretName: foldersync-sshkeys-system
            defaultMode: 0600
        - name: gphoto
          hostPath:
            path: /mnt/user-data-slight/private-data/foldersync/gphoto
            type: Directory
        - name: obsidian
          hostPath:
            path: /mnt/coder-workspaces/private-workspace/repos/local/notebook/obsidian
            type: Directory
      containers:
        - name: app
          image: cloudpublic/default/foldersync:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: foldersync-sshkeys-user-hh
              mountPath: /tmp/foldersync-sshkeys-user-hh
            - name: foldersync-sshkeys-user-cc
              mountPath: /tmp/foldersync-sshkeys-user-cc
            - name: foldersync-sshkeys-user-001
              mountPath: /tmp/foldersync-sshkeys-user-001
            - name: foldersync-sshkeys-system
              mountPath: /tmp/foldersync-sshkeys-system
            - name: gphoto
              mountPath: /mnt/user-data-slight/gphotosync # change me later /data/gphoto
            - name: obsidian
              mountPath: /data/obsidian
          ports:
            - containerPort: 22
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: foldersync
  namespace: default
  labels:
    app: foldersync
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 37000
      protocol: TCP
      targetPort: 22
  selector:
    app: foldersync
