Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000

Metrics/ParameterLists:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 300

# The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
# Please also note that can also opt-in to new cops by default by adding this to your config:
# For more information: https://docs.rubocop.org/rubocop/versioning.html
# hint by vscode
AllCops:
    NewCops: enable
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Style/AsciiComments:
  Enabled: false
