---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray
  namespace: default
  labels:
    app.kubernetes.io/name: xray
data:
  config.json: |
    {
      "log": {
        "loglevel": "warning",
        "access": "/tmp/xray-access.log",
        "error": "/tmp/xray-error.log"
      },
      "inbounds": [
        {
          "tag": "koishi",
          "port": 1081,
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                // run uuidgen
                "id": "__{{v2ray.uuids:f:gopya}}__",
                "alterId": 0
              },
              {
                "id": "__{{v2ray.uuids:f:umbilical}}__",
                "alterId": 0
              },
              {
                "id": "__{{v2ray.uuids:f:sofmacpro}}__",
                "alterId": 0
                "alterId": 0
              },
              {
                "id": "__{{v2ray.uuids:f:cupid}}__",
                "alterId": 0
              }
            ],
            "disableInsecureEncryption": true
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "path": "/kaser"
            }
          }
        },
        {
          "tag": "umbilical",
          "port": 1082,
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "__{{v2ray.uuids:f:sofmacpro}}__",
                "alterId": 0
              }
            ],
            "disableInsecureEncryption": true
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "path": "/uaser"
            }
          }
        }
      ],
      "outbounds": [
        {
          "tag": "direct",
          "protocol": "freedom",
          "settings": {}
        },
        {
          "tag": "wireproxy",
          "protocol": "socks",
          "settings": {
            "servers": [
              {
                "address": "wireproxy.default",
                "port": 1080,
                "users": [
                  {
                    "user": "default",
                    "pass": "__{{wireproxy:f:socks5}}__",
                    "level": 0
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "sockopt": {
              "mark": 255
            }
          }
        }
      ],
      "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
          {
            "type": "field",
            "inboundTag": ["koishi"],
            "outboundTag": "direct"
          },
          {
            "type": "field",
            "inboundTag": ["umbilical"],
            "outboundTag": "wireproxy"
          }
        ]
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
  namespace: default
  labels:
    app.kubernetes.io/name: xray
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xray
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xray
    spec:
      volumes:
        - name: config
          configMap:
            name: xray
      containers:
        - name: app
          image: ghcr.io/xtls/xray-core:25.12.8
          imagePullPolicy: Always
          args: ["run", "-config", "/etc/v2ray/config.json"]
          volumeMounts:
            - name: config
              mountPath: /etc/v2ray/
          ports:
            - name: koishi
              containerPort: 1081
            - name: umbilical
              containerPort: 1082
          resources:
            requests:
              cpu: 150m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: default
  labels:
    app.kubernetes.io/name: xray
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xray
  ports:
    - name: koishi
      protocol: TCP
      port: 1081
      targetPort: koishi
    - name: umbilical
      protocol: TCP
      port: 1082
      targetPort: umbilical

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xray
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
spec:
  ingressClassName: traefik
  rules:
    - host: x.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /kaser
            pathType: Prefix
            backend:
              service:
                name: xray
                port:
                  name: koishi
          - path: /uaser
            pathType: Prefix
            backend:
              service:
                name: xray
                port:
                  name: umbilical
  tls:
    - hosts:
        - x.__{{infra.domains:f:x}}__
      secretName: x-domainx
