---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-prod
  namespace: my-database
  labels:
    app.kubernetes.io/name: db-postgres-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db-postgres-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-postgres-prod
    spec:
      nodeSelector:
        kubernetes.io/hostname: miniba
      volumes:
        - name: data
          hostPath:
            path: /mnt/runtime-data-app/postgres.prod
            type: DirectoryOrCreate
      containers:
        - name: app
          image: postgres:14.2
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "__{{database.postgres.accounts:f:postgres}}__"
            - name: POSTGRES_DB
              value: default
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          ports:
            - name: default
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - pg_isready
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-prod
  namespace: my-database
  labels:
    app.kubernetes.io/name: db-postgres-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db-postgres-prod
  ports:
    - name: default
      port: 5432
      targetPort: default
