---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-dev
  namespace: my-database
  labels:
    app.kubernetes.io/name: db-postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db-postgres-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-postgres-dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: nur
      volumes:
        - name: data
          hostPath:
            path: /mnt/runtime-data-app/postgres.dev
            type: DirectoryOrCreate
      containers:
        - name: app
          image: postgres:18
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "__{{database.postgres-dev.accounts:f:postgres}}__"
            - name: POSTGRES_DB
              value: default
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          ports:
            - name: default
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - pg_isready
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-dev
  namespace: my-database
  labels:
    app.kubernetes.io/name: db-postgres-dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db-postgres-dev
  ports:
    - name: default
      port: 5432
      targetPort: default

---
# for cc access from macm4
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-dev-cc
  namespace: my-database
  labels:
    app.kubernetes.io/name: tool-dbgate-cc
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/name: db-postgres-dev
  ports:
    - port: 37290
      protocol: TCP
      targetPort: 5432
