---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: my-database
data:
  create-users.sql: |
    CREATE DATABASE coder;
    CREATE USER coder WITH PASSWORD '__{{database.postgres.accounts:f:coder}}__';
    GRANT ALL PRIVILEGES ON DATABASE coder TO coder;
    CREATE DATABASE guacamole;
    CREATE USER guacamole WITH PASSWORD '__{{database.postgres.accounts:f:guacamole}}__';
    GRANT ALL PRIVILEGES ON DATABASE guacamole TO guacamole;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
  namespace: my-database
  labels:
    app: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: nippon
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
        - name: data
          hostPath:
            path: /mnt/runtime-data-app/postgres
            type: DirectoryOrCreate
      containers:
        - name: app
          image: postgres:14.2
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "__{{database.postgres.accounts:f:postgres}}__"
            - name: POSTGRES_DB
              value: default
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/postgresql/data
          ports:
            - name: default
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - pg_isready
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: my-database
  labels:
    app: db-postgres
spec:
  type: ClusterIP
  selector:
    app: db-postgres
  ports:
    - name: default
      port: 5432
      targetPort: default
