---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: default
  labels:
    app: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samba
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - rclone
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: user-data-music
          hostPath:
            path: /mnt/user-data-music
            type: DirectoryOrCreate
        - name: user-data-others
          persistentVolumeClaim:
            claimName: nfs-disk-user-data-others
        - name: nfs-data-download
          persistentVolumeClaim:
            claimName: nfs-data-download
        - name: user-data-slight
          persistentVolumeClaim:
            claimName: nfs-disk-user-data-slight
        - name: remote
          hostPath:
            path: /mnt/remote
            type: DirectoryOrCreate
        - name: webdav
          hostPath:
            path: /mnt/webdav
            type: DirectoryOrCreate
        - name: decrypted
          hostPath:
            path: /mnt/decrypted
            type: DirectoryOrCreate
      containers:
        - name: app
          image: cloudpublic/media/samba:latest
          imagePullPolicy: Always
          args: [
              "-n",
              "-S",
              "-r",
              "-p", # Set ownership and permissions on the shares
              "-u",
              "__{{infra.common-users:f:hh}}__;__{{samba.user.hh}}__",
              "-u",
              "__{{infra.common-users:f:cc}}__;__{{samba.user.cc}}__",
              "-s",
              "LocalSharePoint;/mnt/user-data-slight/share-point;yes;no;yes",
            ]
          env:
            - name: GLOBAL1
              value: "smb encrypt = desired"
            - name: GLOBAL2
              value: "vfs objects = acl_xattr"
            - name: GLOBAL3
              value: "map archive = no"
            - name: GLOBAL4
              value: "local master = no"
            - name: GLOBAL5
              value: "domain master = no"
            - name: GLOBAL6
              value: "store dos attributes = yes"
            - name: GLOBAL7
              value: "create mask = 0744"
            - name: GLOBAL8
              value: "directory mask = 0755"
            - name: GLOBAL9
              value: "socket options = TCP_NODELAY SO_RCVBUF=8192 SO_SNDBUF=8192"
            - name: GLOBAL10
              value: "deadtime = 15"
            - name: GLOBAL11
              value: "keepalive = 30"
            - name: GLOBAL12
              value: "max connections = 100"
          volumeMounts:
            - name: user-data-music
              mountPath: /mnt/user-data-music/upload
              subPath: upload
            - name: user-data-others
              mountPath: /mnt/user-data-others/upload
              subPath: upload
            - name: user-data-others
              mountPath: /mnt/user-data-others/data
              subPath: data
              readOnly: true
            - name: user-data-others
              mountPath: /mnt/user-data-others/workspace
              subPath: workspace
            - name: user-data-slight
              mountPath: /mnt/user-data-slight/private-data
              subPath: private-data
            - name: user-data-slight
              mountPath: /mnt/user-data-slight/upload
              subPath: upload
            - name: user-data-slight
              mountPath: /mnt/user-data-slight/share-point
              subPath: share-point
            - name: remote
              mountPath: /mnt/remote
            - name: webdav
              mountPath: /mnt/webdav
            - name: decrypted
              mountPath: /mnt/decrypted
            - name: nfs-data-download
              mountPath: /mnt/nfs-data/download
          ports:
            - containerPort: 137
            - containerPort: 138
            - containerPort: 139
            - containerPort: 445
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                ["bash", "health-check.sh", "/mnt/user-data-slight/share-point"]
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: default
  labels:
    app: samba
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  type: LoadBalancer
  selector:
    app: samba
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: p137
      protocol: UDP
      port: 137
      targetPort: 137
    - name: p138
      protocol: UDP
      port: 138
      targetPort: 138
    - name: p139
      protocol: TCP
      port: 139
      targetPort: 139
    - name: p445
      protocol: TCP
      port: 445
      targetPort: 445
