# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# zmodload zsh/zprof  # for profiling
export LC_CTYPE=en_US.UTF-8                             #It should be the same as locale-gen.
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

SYSTEM=`uname -s`

# ---------------------------------------------
# ENV
# ---------------------------------------------
export TERM=xterm-256color
export PATH=/snap/bin:/usr/local/sbin:~/.local/bin:~/go/bin:~/bin:~/scripts/workspace:~/scripts/workspace/third-part:~/scripts/dev:~/.config/emacs/bin:$PATH
export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))

if [ $SYSTEM = "Linux" ]; then
    export EDITOR='vim'

    # make docker-compose to use build kit
    export COMPOSE_DOCKER_CLI_BUILD=1
    export DOCKER_BUILDKIT=1
elif [ $SYSTEM = "Darwin" ]; then
    export EDITOR='vim'

    export ANDROID_HOME=~/Library/Android/sdk
    export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator

    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
# ---------------------------------------------

# ---------------------------------------------
# Configuration for history
# ---------------------------------------------
# Number of history entries
export HISTSIZE=5000
# Number of history entries to save after logout
export SAVEHIST=5000
export HISTFILE=~/.zsh/zhistory

# remove duplicated commands
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

# Add timestamp to commands in history
setopt EXTENDED_HISTORY

# Enable history for cd command, cd -[TAB] to enter historic paths
setopt AUTO_PUSHD
# Keep only one of the duplicate historic paths
setopt PUSHD_IGNORE_DUPS

# Add space before command to prevent it from being saved to the history file
setopt HIST_IGNORE_SPACE
# ---------------------------------------------

# ---------------------------------------------
# MISC
# ---------------------------------------------
# Allow comments in interactive shell, e.g. $ cmd #this is a comment
setopt INTERACTIVE_COMMENTS

# Enable auto CD: press Enter on a directory name to navigate into it
setopt AUTO_CD

# Path expansion
# /v/c/p/p => /var/cache/pacman/pkg
setopt complete_in_word

# Key bindings: -e for Emacs, -v for Vim
bindkey -e

# Consider the following characters as part of a word
WORDCHARS='*?_-[]~=&;!#$%^(){}<>'

setopt EXTENDED_GLOB

# no hint if match file and directory
# setopt correctall
setopt nocorrectall
setopt correct


# Replace default push-line with push-line-or-edit
bindkey "\eq" push-line-or-edit

# mkdir, cd into it
mkcd () {
    mkdir -p "$*"
    cd "$*"
}

# ---------------------------------------------

# --------------------------------------------------------------
# Move by shell arguments
# http://lilydjwg.is-programmer.com/posts/41712
# --------------------------------------------------------------
# move by shell word
zsh-word-movement () {
  # see select-word-style for more
  local -a word_functions
  local f

  word_functions=(backward-kill-word backward-word
    capitalize-word down-case-word
    forward-word kill-word
    transpose-words up-case-word)

  if ! zle -l $word_functions[1]; then
    for f in $word_functions; do
      autoload -Uz $f-match
      zle -N zsh-$f $f-match
    done
  fi
  # set the style to shell
  zstyle ':zle:zsh-*' word-style shell
}
zsh-word-movement
unfunction zsh-word-movement
bindkey "\eB" zsh-backward-word
bindkey "\eF" zsh-forward-word
bindkey "\eW" zsh-backward-kill-word
# --------------------------------------------------------------

# ---------------------------------------------
# auto complete
# ---------------------------------------------
autoload compinstall

# setopt AUTO_LIST
# setopt AUTO_MENU

autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# Autocomplete cache
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path .zcache
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# Autocomplete options
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select
zstyle ':completion:*:*:default' force-list always
zstyle ':completion:*' select-prompt '%SSelect:  lines: %L  matches: %M  [%p]'

zstyle ':completion:*:match:*' original only
zstyle ':completion::prefix-1:*' completer _complete
zstyle ':completion:predict:*' completer _complete
zstyle ':completion:incremental:*' completer _complete _correct
zstyle ':completion:*' completer _complete _prefix _correct _prefix _match _approximate

# Path completion
zstyle ':completion:*' expand 'yes'
zstyle ':completion:*' squeeze-shlashes 'yes'
zstyle ':completion::complete:*' '\\'

# Colored completion menu
if [ -x /usr/bin/dircolors ]; then
    eval $(dircolors -b)
    export ZLSCOLORS="${LS_COLORS}"
    zmodload zsh/complist
    zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
    zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
fi

# Case correction
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
# Error correction
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# Group completion type descriptions
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format $'\e[01;33m -- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[01;35m -- %d --\e[0m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found --\e[0m'
zstyle ':completion:*:corrections' format $'\e[01;32m -- %d (errors: %e) --\e[0m'

# cd ~ completion order
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'

# Completion for ssh, scp, sftp, etc.
zstyle -e ':completion::*:*:*:hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

export FPATH=/mnt/coder-workspaces/private-workspace/repos/local/polyphony/devconfigs/repos/oh-my-zsh/custom/completions:$FPATH
# ---------------------------------------------

# ---------------------------------------------
# Line editing highlight modes
# Ctrl+@ sets a mark; the area between the mark and the cursor is a region
# ---------------------------------------------
zle_highlight=(region:bg=magenta    #Selected region
special:bold                        #Special characters
isearch:underline)                  #Keywords used during search
# ---------------------------------------------

# ---------------------------------------------
# Insert sudo before the command
# ---------------------------------------------
# Define function
sudo-command-line() {
[[ -z $BUFFER ]] && zle up-history
[[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
zle end-of-line                 #Move cursor to end of line
}
zle -N sudo-command-line
# Define shortcut key: [Esc] [Esc]
bindkey "\e\e" sudo-command-line
# ---------------------------------------------

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ssh='ssh -A'
alias e='LC_ALL=zh_CN.UTF-8 emacs -nw'
alias lg='lazygit'
alias claude='SHELL=/bin/bash claude'
alias c='bash ~/.kube/get-token.devbox-user.sh session >/dev/null && SHELL=/bin/bash claude'
alias a='bash ~/.kube/get-token.devbox-user.sh session >/dev/null && agy'
alias g='bash ~/.kube/get-token.devbox-user.sh session >/dev/null && gemini'
alias 9='bash ~/.kube/get-token.devbox-user.sh session >/dev/null && k9s'

# do not use python3 in nix
alias python3="$(which python3.12)"
alias pytest="/home/box/.asdf/shims/pytest"

alias docker='sudo DOCKER_CONFIG=/home/box/.docker docker'

# Changing "ls" to "eza"
alias ls='eza --color=always --group-directories-first'
alias la='eza -a --color=always --group-directories-first'    # all files and dirs
alias ll='eza -l --color=always --group-directories-first'    # long format
alias lla='eza -al --color=always --group-directories-first'  # long format with all files and dirs
alias lt='eza -aT --color=always --group-directories-first'   # tree listing
alias l.='eza -a | egrep "^\."'                               # all dot files

if [ $SYSTEM = "Linux" ]; then
    alias ls='ls --color=auto'
elif [ $SYSTEM = "Darwin" ]; then
    alias ls='ls -Gv'
fi

# cd ~xxx
hash -d workspace="$HOME/private-workspace/workspace"
hash -d doom="$HOME/private-workspace/repos/local/doom.d"

# ---------------------------------------------
# go
# ---------------------------------------------
export GOPATH=$HOME/go
export PATH=/usr/local/go/bin:$PATH
# ---------------------------------------------

# ---------------------------------------------
# Rust
# ---------------------------------------------
[[ -s "$HOME/.cargo/env" ]] && . $HOME/.cargo/env
# ---------------------------------------------

if command -v fzf > /dev/null ; then
  source $(dirname $(dirname $(which fzf)))/share/fzf/completion.zsh
  source $(dirname $(dirname $(which fzf)))/share/fzf/key-bindings.zsh
fi

# ---------------------------------------------
# iTerm2
# ---------------------------------------------
test -e "${HOME}/public-workspace/dev-config/configs/iterm2/iterm2_shell_integration.zsh" && source ${HOME}/public-workspace/dev-config/configs/iterm2/iterm2_shell_integration.zsh || true
# ---------------------------------------------

# ---------------------------------------------
# kubernetes
# ---------------------------------------------
export KUBECONFIG=$HOME/.kube/config
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)
alias k=kubectl
compdef __start_kubectl k
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# linkerd
export PATH=$HOME/.linkerd2/bin:$PATH


export MY_KUBECTL_SESSION_KEY=$(tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c 14)
export MY_KUBECTL_SESSION_FILE=$(mktemp)


alias kns='kubens'
alias kctx='kubectx'
# ---------------------------------------------

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
  # TODO: not working sometimes
  source $HOME/.nix-profile/etc/profile.d/nix.sh
  if ! command -v nix-shell > /dev/null; then
    export PATH=$HOME/.nix-profile/bin:$PATH
  fi

  export NIXPKGS_ALLOW_UNFREE=1
  nshell () {
    nix-shell $HOME/default.nix --run 'zsh'
  }
fi

if command -v zoxide > /dev/null ; then
  eval "$(zoxide init --cmd cd zsh)"
fi

if [[ -f $HOME/.asdf/asdf.sh ]]; then
  . "$HOME/.asdf/asdf.sh"
fi

command_not_found_handler() {
  cmd="nix-shell -p $1 --run $1"
  echo "'$1' not found. You can install it by press Ctrl+N"
  echo "${cmd}"
  echo "${cmd}" > /tmp/zsh.command_not_found_handler.cmd_last_not_found
  exit 1
}

function insert_cmd_last_not_found() {
  print -z "$(cat /tmp/zsh.command_not_found_handler.cmd_last_not_found)"
}

zle -N insert_cmd_last_not_found
bindkey "^n" insert_cmd_last_not_found


export PATH="$PATH:/opt/nvim/bin"
if command -v nvim > /dev/null ; then
  alias n="nvim"
fi

if [ -d ~/bin/flutter ]; then
    export PATH=~/bin/flutter/bin:$PATH
fi

if [ -d $HOME/.pub-cache/bin ]; then
    export PATH=$HOME/.pub-cache/bin:$PATH
fi


if [ -d ~/bin/android-sdk/cmdline-tools/latest/bin ]; then
    export ANDROID_SDK_ROOT=$HOME/bin/android-sdk
    export ANDROID_HOME=$HOME/bin/android-sdk
    export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
    export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
    export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
fi

if [ -d ~/bin/npm-packages/bin ]; then
    export PATH=$HOME/bin/npm-packages/bin:$PATH
fi

if [ -d ~/bin/npm-packages/lib/node_modules ]; then
    export NODE_PATH=$HOME/bin/npm-packages/lib/node_modules
fi

export TZ=Asia/Tokyo

export LC_TIME=en_GB.UTF-8

export PATH="/home/box/scripts/koishi:$PATH"

# Added by Antigravity CLI installer
export PATH="/home/box/.local/bin:$PATH"

source /mnt/coder-workspaces/private-workspace/repos/local/polyphony/devconfigs/envs/private_env.sh

# zprof #  for profiling
