---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-postgres
  namespace: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dify-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: nur
      containers:
        - name: postgres
          image: postgres:16.6
          env:
            - name: POSTGRES_USER
              value: dify
            - name: POSTGRES_PASSWORD
              value: "TPSTUvntXQ1fK6nIl-fF"
            - name: POSTGRES_DB
              value: dify
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dify-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dify-postgres
  namespace: dify
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: dify-postgres
