---
apiVersion: v1
kind: Service
metadata:
  name: devbox-nur-itero
  namespace: default
  labels:
    app: devbox-nur-itero
spec:
  type: ClusterIP
  selector:
    app: devbox-nur
  ports:
    - name: default
      port: 3250
      protocol: TCP
      targetPort: 3250

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itero
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: middleware-playonjan@kubernetescrd,middleware-antimitm@kubernetescrd,sso-domainx@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: AI
    gethomepage.dev/name: Itero
    gethomepage.dev/href: https://itero.__{{infra.domains:f:x}}__/
    gethomepage.dev/weight: "5"
spec:
  ingressClassName: traefik
  rules:
    - host: itero.__{{infra.domains:f:x}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devbox-nur-itero
                port:
                  name: default
  tls:
    - hosts:
        - itero.__{{infra.domains:f:x}}__
      secretName: itero-domainx
