---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip2location
  namespace: default
  labels:
    app: ip2location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip2location
  template:
    metadata:
      labels:
        app: ip2location
    spec:
      containers:
        - name: app
          image: cloudpublic/default/ip2location:latest
          imagePullPolicy: Always
          ports:
            - name: default
              containerPort: 8080
          resources:
            requests:
              cpu: 20m
              memory: 32Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ip2location
  namespace: default
  labels:
    app: ip2location
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: default
  selector:
    app: ip2location

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip2location
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-letsencrypt-dns-cloudflare
spec:
  ingressClassName: traefik
  rules:
    - host: ip2location.home4p.__{{koishi.base.domain1}}__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip2location
                port:
                  name: default
  tls:
    - hosts:
        - ip2location.home4p.__{{koishi.base.domain1}}__
      secretName: ip2location-home4p
