---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-external-creds
  namespace: db-dev
type: Opaque
stringData:
  username: postgres
  password: "__{{database.postgres-dev.accounts:f:postgres}}__"

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db-dev
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - "*"
        source:
          externalCluster: postgres-old
      # インポート開始前にロールを作成
      postInitSQL:
        - CREATE ROLE nulltrace WITH LOGIN;
        - CREATE ROLE formant WITH LOGIN;
        - CREATE ROLE kausabu WITH LOGIN;
        - CREATE ROLE home WITH LOGIN;
        - CREATE ROLE pushion WITH LOGIN;
        - CREATE ROLE forma WITH LOGIN;

  externalClusters:
    - name: postgres-old
      connectionParameters:
        host: postgres.db-dev.svc.cluster.local
        user: postgres
        dbname: default
        sslmode: disable
      password:
        name: postgres-external-creds
        key: password

  storage:
    size: 1Gi
    storageClass: local-path

  monitoring:
    enablePodMonitor: true

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster
  namespace: db-dev
  labels:
    app.kubernetes.io/name: postgres-cluster
    cnpg.io/cluster: postgres-cluster
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
