package handler

const dashboardHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>webreader dashboard</title><style>
body{font:14px system-ui,sans-serif;max-width:1200px;margin:32px auto;padding:0 16px;background:#f7f8fa;color:#20242b}h1{margin-bottom:4px}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card,.request{background:#fff;border:1px solid #dfe3e8;border-radius:8px;padding:14px}.number{font-size:24px;font-weight:700}.request{display:block;width:100%;margin:10px 0;text-align:left;cursor:pointer;color:inherit}.request:hover{border-color:#98a2b3;background:#fcfcfd}.url{word-break:break-all;font-weight:600}.state{float:right;border-radius:12px;padding:2px 8px;background:#e8edf3}pre{overflow:auto;white-space:pre-wrap;word-break:break-word;background:#f5f6f8;padding:12px;border-radius:5px}button{padding:7px 10px}#updated{margin-left:8px}dialog{width:min(900px,calc(100vw - 32px));max-height:85vh;overflow-x:hidden;border:0;border-radius:10px;box-shadow:0 12px 48px #0005}dialog::backdrop{background:#0007}.dialog-head{display:flex;justify-content:space-between;align-items:start;gap:16px;min-width:0}.dialog-head h2{min-width:0;margin-top:0;overflow-wrap:anywhere}
</style></head><body><h1>webreader dashboard</h1><p class="muted">Process-local request history. It is cleared when this service restarts.</p>
<div class="grid" id="stats"></div><h2>Queued requests</h2><div id="queue" class="muted">Loading…</div><h2>Recent requests</h2><div id="history"></div>
<button onclick="load()">Refresh</button><span id="updated" class="muted"></span>
<dialog id="request-dialog"><div class="dialog-head"><h2 id="dialog-title">Request</h2><form method="dialog"><button>Close</button></form></div><div id="dialog-body"></div></dialog>
<script>
function esc(value){const d=document.createElement('div');d.textContent=value==null?'':String(value);return d.innerHTML}
let records=new Map()
function record(r){return '<button class="request" onclick="showRequest('+r.id+')"><span class="state">'+esc(r.state)+'</span><span class="url">'+esc(r.url)+'</span><br><span class="muted">'+esc(r.started_at)+'</span></button>'}
function showRequest(id){const r=records.get(id);if(!r)return;document.getElementById('dialog-title').textContent=r.url;const result=r.result?'<h3>Cached response</h3><pre>'+esc(JSON.stringify(r.result,null,2))+'</pre>':'';const error=r.error?'<h3>Error</h3><pre>'+esc(r.error)+'</pre>':'';document.getElementById('dialog-body').innerHTML='<p><span class="state">'+esc(r.state)+'</span></p><h3>Parameters</h3><pre>'+esc(JSON.stringify(r.parameters,null,2))+'</pre>'+result+error;document.getElementById('request-dialog').showModal()}
async function load(){try{const d=await fetch('/v1/dashboard',{cache:'no-store'}).then(r=>r.json());records=new Map([...d.history,...d.queued_requests].map(r=>[r.id,r]));document.getElementById('stats').innerHTML=[['Active requests',d.status.active_requests],['Waiting requests',d.status.waiting_requests],['Max concurrent',d.status.max_concurrent],['Requests/minute',d.status.requests_per_minute]].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="number">'+x[1]+'</div></div>').join('');document.getElementById('queue').innerHTML=d.queued_requests.length?d.queued_requests.map(record).join(''):'No requests are waiting.';document.getElementById('history').innerHTML=d.history.length?d.history.map(record).join(''):'No request history yet.';document.getElementById('updated').textContent='Updated '+new Date().toLocaleTimeString()}catch(e){document.getElementById('updated').textContent='Unable to load dashboard: '+e}}
load();setInterval(load,2000);
</script></body></html>`
